### ISSUE TITLE
Request of adding new works

### ISSUE THREAD

**Issue by hyc9** [enoche/MultimodalRecSys#2]
Thanks for your great work on multimodal recommendation systems! 

We've compiled several datasets contributing to this field:
- [PixelRec]  (https://github.com/westlake-repl/PixelRec)
- [MicroLens] (https://github.com/westlake-repl/MicroLens)
- [NineRec] (https://github.com/westlake-repl/NineRec)

A pull request has been submitted for their inclusion in your repository.
We hope you find these additions suitable.

**Comment by enoche** [comment]
@hyc9 Thanks for enriching the domain with more datasets. :)
