### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by fajieyuan** [enoche/MultimodalRecSys#4]
Hi Xin,

I just added two new papers published in SIGIR2023 and WSDM2024 with code, hope you can allow  the update for this great repo.

Many thanks for this useful repo.

Best

**Comment by enoche** [comment]
@fajieyuan Hi, fajie. Thanks for your contribution on this repo. and congrat. on the honored papers. You are encouraged to send a pull request and I will update the new papers as well as datasets into the repo. Thanks.

It seems @hyc9 has contributed with 3 new datasets last week~ :)

**Comment by fajieyuan** [comment]
oh yes,  
hyc9 told me about this.  These are pretty much our last papers on Recsys. We have shifted our research focus to AI4 life sciences. There papers are quite expensive in terms of computation, especially the datasets, hopefully they are useful to our Recsys community.

**Comment by enoche** [comment]
Hi @fajieyuan. A big thanks for your contribution! Your datasets and models are really making the Recsys community a richer place. Can't wait to see you pioneer and thrive in your new research domain. Rock on~
